import type { Metadata } from "next";
import NavBar from "@/components/NavBar/NavBar";
import { Providers } from "@/components/Providers";
import "./globals.css";


export const metadata: Metadata = {
  title: {
    default: "Joyenda | Home",
    template: "Joyenda | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className="dark:bg-[#181818] dark:text-white ">
        <Providers >
          <NavBar />
          {children}
        </Providers>
        </div>
      </body>
    </html>
  );
}
